Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: ScyllaStressTest
  StressSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
          - "0"
          - Fn::GetAZs: !Ref AWS::Region    
      VpcId: !Ref Vpc
      CidrBlock: 10.10.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: ScyllaStressSubnetA
  StressRoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: ScyllaStressTest
  SubnetARouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref StressSubnetA
      RouteTableId: !Ref StressRoutingTable
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: ScyllaStressTest
  VPCIGWAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref Vpc
  DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref StressRoutingTable
    DependsOn: VPCIGWAttach

Outputs:
  VpcId:
    Description: VPC Id
    Value: !Ref Vpc
    Export: 
      Name: !Join [ ":", [ !Ref AWS::StackName, Vpc ] ]
  SubnetId:
      Value: !Ref StressSubnetA
      Description: Subnet A
      Export:
        Name: !Join [ ":", [ !Ref AWS::StackName, StressSubnetA ] ]
  AccoundId:
    Value: !Ref AWS::AccountId
  VPCCidr:
    Value: !GetAtt Vpc.CidrBlock